-- ============================================================
-- Fantasy Draft Assistant -- seed data
-- 32 NFL teams + 419 players + 2026 half-PPR rankings + context notes
-- Run AFTER the schema migration has been applied.
-- Safe to run once on a fresh database; re-running will fail on
-- the unique constraints rather than silently duplicating data.
-- ============================================================

-- ---------- Teams ----------
insert into teams (team_id, team_name, conference, division, bye_week) values
('ARI','Arizona Cardinals','NFC','West',14),
('ATL','Atlanta Falcons','NFC','South',11),
('BAL','Baltimore Ravens','AFC','North',13),
('BUF','Buffalo Bills','AFC','East',7),
('CAR','Carolina Panthers','NFC','South',5),
('CHI','Chicago Bears','NFC','North',10),
('CIN','Cincinnati Bengals','AFC','North',6),
('CLE','Cleveland Browns','AFC','North',11),
('DAL','Dallas Cowboys','NFC','East',14),
('DEN','Denver Broncos','AFC','West',10),
('DET','Detroit Lions','NFC','North',6),
('GB','Green Bay Packers','NFC','North',11),
('HOU','Houston Texans','AFC','South',8),
('IND','Indianapolis Colts','AFC','South',13),
('JAX','Jacksonville Jaguars','AFC','South',7),
('KC','Kansas City Chiefs','AFC','West',5),
('LAC','Los Angeles Chargers','AFC','West',7),
('LAR','Los Angeles Rams','NFC','West',11),
('LV','Las Vegas Raiders','AFC','West',13),
('MIA','Miami Dolphins','AFC','East',6),
('MIN','Minnesota Vikings','NFC','North',6),
('NE','New England Patriots','AFC','East',11),
('NO','New Orleans Saints','NFC','South',8),
('NYG','New York Giants','NFC','East',8),
('NYJ','New York Jets','AFC','East',13),
('PHI','Philadelphia Eagles','NFC','East',10),
('PIT','Pittsburgh Steelers','AFC','North',9),
('SEA','Seattle Seahawks','NFC','West',11),
('SF','San Francisco 49ers','NFC','West',8),
('TB','Tampa Bay Buccaneers','NFC','South',10),
('TEN','Tennessee Titans','AFC','South',9),
('WAS','Washington Commanders','NFC','East',7);

-- ---------- Players, rankings, and initial context notes ----------
with source_data (full_name, position, team_id, overall_rank, position_rank, proj_ppg, note_text) as (
  values
  ('Ja''Marr Chase','WR','CIN',1,1,23.5,'Top-5 WR in points per game in 4 of the last 5 seasons'),
  ('Jahmyr Gibbs','RB','DET',2,1,23.1,'Lead-back workload after Montgomery was traded away; elite receiving work'),
  ('Puka Nacua','WR','LAR',3,2,20.9,'Elite target volume; under personal-conduct-policy review for a civil lawsuit, suspension possible but consensus expects at most 1-2 games'),
  ('Bijan Robinson','RB','ATL',4,2,20.6,'Led the NFL in scrimmage yards last season'),
  ('Jaxon Smith-Njigba','WR','SEA',5,3,19.6,'Finished as the WR2 in total scoring last season'),
  ('Jonathan Taylor','RB','IND',6,3,19.4,'Workhorse volume, elite per-touch efficiency'),
  ('James Cook III','RB','BUF',7,4,19.1,'Led the NFL in rushing yards in 2025'),
  ('Amon-Ra St. Brown','WR','DET',8,4,18.4,'Elite target share in Detroit''s offense'),
  ('Christian McCaffrey','RB','SF',9,5,18.4,'Handled a 300+ touch workload again in 2025 and held up'),
  ('Justin Jefferson','WR','MIN',10,5,17.2,'Dominant with every QB except last year; buy-low with Kyler Murray now throwing to him'),
  ('CeeDee Lamb','WR','DAL',11,6,17.2,'Now sharing targets with new arrival George Pickens'),
  ('Saquon Barkley','RB','PHI',12,6,17.1,'Eagles'' clear offensive centerpiece'),
  ('Chase Brown','RB','CIN',13,7,17.1,'Bengals'' lead back'),
  ('Malik Nabers','WR','NYG',14,7,16.4,'On track to return for Week 1 off last year''s ACL tear'),
  ('Drake London','WR','ATL',15,8,16.4,'Falcons'' clear WR1'),
  ('De''Von Achane','RB','MIA',16,8,16.1,'Explosive but a crowded, evolving Miami backfield'),
  ('Derrick Henry','RB','BAL',17,9,15.9,'Elite production continuing into his 30s'),
  ('Nico Collins','WR','HOU',18,9,15.6,'Houston''s top target; Jayden Higgins'' season-ending injury raises his target share further'),
  ('Kenneth Walker III','RB','KC',19,10,15.8,'Signed with Kansas City this offseason; new backfield role'),
  ('A.J. Brown','WR','NE',20,10,15.5,'Traded to New England this offseason to pair with Drake Maye'),
  ('George Pickens','WR','DAL',21,11,15.5,'Now in Dallas, sharing targets with CeeDee Lamb'),
  ('Omarion Hampton','RB','LAC',22,11,15.3,'Rookie standout, Chargers'' clear lead back'),
  ('Ashton Jeanty','RB','LV',23,12,15.3,'Year-2 back, expectations rise after a solid rookie season'),
  ('Rashee Rice','WR','KC',24,12,15.0,'Missed minicamp time tied to a legal matter; scheme change may also affect usage'),
  ('Jeremiyah Love','RB','ARI',25,13,15.0,'Rookie, drafted 3rd overall; battling an ankle sprain in camp'),
  ('Chris Olave','WR','NO',26,13,15.0,'Saints'' top receiving option'),
  ('Javonte Williams','RB','DAL',27,14,14.5,'Cowboys'' lead back after Jaydon Blue''s release'),
  ('Zay Flowers','WR','BAL',28,14,14.3,'Ravens'' primary slot/target earner'),
  ('Travis Etienne Jr.','RB','NO',29,15,14.5,'Now with New Orleans after 1,107 rush yards last season'),
  ('Tee Higgins','WR','CIN',30,15,14.3,'Bengals'' co-WR1 alongside Chase'),
  ('Jaylen Waddle','WR','DEN',31,16,14.3,'Traded from Miami to Denver this offseason'),
  ('Breece Hall','RB','NYJ',32,16,13.9,'Jets'' pass-catching back'),
  ('DeVonta Smith','WR','PHI',33,17,14.3,'Eagles'' reliable possession receiver'),
  ('D''Andre Swift','RB','CHI',34,17,13.9,'Efficient 2025 (4.9 YPA); Bears'' lead back'),
  ('Ladd McConkey','WR','LAC',35,18,14.2,'Chargers'' emerging top target'),
  ('Kyren Williams','RB','LAR',36,18,13.9,'Rams'' primary ball-carrier'),
  ('Emeka Egbuka','WR','TB',37,19,14.2,'Opportunity opened up after Mike Evans left for San Francisco'),
  ('Cam Skattebo','RB','NYG',38,19,13.1,'Giants rookie who forced his way into a real role'),
  ('Terry McLaurin','WR','WAS',39,20,14.2,'Washington''s veteran WR1'),
  ('David Montgomery','RB','HOU',40,20,12.8,'Traded from Detroit to Houston; strong goal-line value'),
  ('Tetairoa McMillan','WR','CAR',41,21,14.2,'Sophomore receiver, Panthers'' top target'),
  ('Bhayshul Tuten','RB','JAX',42,21,12.8,'Jaguars committee piece with speed upside'),
  ('Garrett Wilson','WR','NYJ',43,22,14.2,'Jets'' clear WR1'),
  ('Quinshon Judkins','RB','CLE',44,22,12.8,'Browns'' young building-block back'),
  ('Luther Burden III','WR','CHI',45,23,14.2,'Bears rookie carving out a role'),
  ('Jadarian Price','RB','SEA',46,23,12.4,'Seahawks'' outright lead back after Zach Charbonnet went to PUP'),
  ('Parker Washington','WR','JAX',47,24,13.2,'WR depth piece per current 53-man roster; 13.2 proj PPG (PFN consensus, not individually researched)'),
  ('Bucky Irving','RB','TB',48,24,12.4,'Buccaneers'' lead back'),
  ('Christian Watson','WR','GB',49,25,13.2,'High-upside but notable injury history'),
  ('Jaylen Warren','RB','PIT',50,25,11.9,'Steelers'' primary back'),
  ('Jameson Williams','WR','DET',51,26,13.2,'Lions'' deep-threat complement to St. Brown'),
  ('Rhamondre Stevenson','RB','NE',52,26,11.9,'Patriots'' veteran early-down back'),
  ('Rome Odunze','WR','CHI',53,27,13.2,'WR depth piece per current 53-man roster; 13.2 proj PPG (PFN consensus, not individually researched)'),
  ('TreVeyon Henderson','RB','NE',54,27,11.9,'Rookie complement in New England''s backfield'),
  ('Carnell Tate','WR','TEN',55,28,12.1,'First rookie WR off the board in most 2026 drafts'),
  ('Chuba Hubbard','RB','CAR',56,28,11.6,'Panthers'' lead back; dealt with a camp hamstring issue'),
  ('Marvin Harrison Jr.','WR','ARI',57,29,12.1,'Cardinals'' year-2 receiver'),
  ('Tony Pollard','RB','TEN',58,29,10.5,'Titans'' veteran back'),
  ('DJ Moore','WR','BUF',59,30,12.1,'Traded from Chicago to Buffalo this offseason'),
  ('Kenny Gainwell','RB','TB',60,30,10.5,'Buccaneers backfield depth/passing-down role'),
  ('Davante Adams','WR','LAR',61,31,12.1,'Now with the Rams alongside Puka Nacua'),
  ('Jonathon Brooks','RB','CAR',62,31,10.5,'Returning from a second ACL tear in 13 months'),
  ('Josh Downs','WR','IND',63,32,12.1,'WR depth piece per current 53-man roster; 12.1 proj PPG (PFN consensus, not individually researched)'),
  ('Jacory Croskey-Merritt','RB','WAS',64,32,10.5,'RB depth piece per current 53-man roster; 10.5 proj PPG (PFN consensus, not individually researched)'),
  ('DK Metcalf','WR','PIT',65,33,12.1,'Now with Pittsburgh'),
  ('Rico Dowdle','RB','PIT',66,33,10.5,'Steelers change-of-pace option'),
  ('Brian Thomas Jr.','WR','JAX',67,34,11.7,'Jaguars'' big-play target'),
  ('MarShawn Lloyd','RB','GB',68,34,10.5,'RB depth piece per current 53-man roster; 10.5 proj PPG (PFN consensus, not individually researched)'),
  ('Michael Pittman Jr.','WR','PIT',69,35,11.7,'Signed with Pittsburgh this offseason'),
  ('Blake Corum','RB','LAR',70,35,10.5,'RB depth piece per current 53-man roster; 10.5 proj PPG (PFN consensus, not individually researched)'),
  ('Quentin Johnston','WR','LAC',71,36,11.7,'WR depth piece per current 53-man roster; 11.7 proj PPG (PFN consensus, not individually researched)'),
  ('Jordan Mason','RB','MIN',72,36,9.9,'RB depth piece per current 53-man roster; 9.9 proj PPG (PFN consensus, not individually researched)'),
  ('Mike Evans','WR','SF',73,37,11.7,'Traded from Tampa Bay to San Francisco'),
  ('Kyle Monangai','RB','CHI',74,37,9.9,'RB depth piece per current 53-man roster; 9.9 proj PPG (PFN consensus, not individually researched)'),
  ('Jayden Reed','WR','GB',75,38,11.7,'WR depth piece per current 53-man roster; 11.7 proj PPG (PFN consensus, not individually researched)'),
  ('Rachaad White','RB','WAS',76,38,9.3,'RB depth piece per current 53-man roster; 9.3 proj PPG (PFN consensus, not individually researched)'),
  ('Stefon Diggs','WR','WAS',77,39,11.7,'Signed with Washington in early August'),
  ('J.K. Dobbins','RB','DEN',78,39,8.7,'Stuck in a real three-way Denver committee with RJ Harvey and rookie Jonah Coleman'),
  ('Jakobi Meyers','WR','JAX',79,40,11.7,'WR depth piece per current 53-man roster; 11.7 proj PPG (PFN consensus, not individually researched)'),
  ('RJ Harvey','RB','DEN',80,40,8.7,'RB depth piece per current 53-man roster; 8.7 proj PPG (PFN consensus, not individually researched)'),
  ('Wan''Dale Robinson','WR','TEN',81,41,10.4,'Signed with Tennessee this offseason'),
  ('Chris Rodriguez Jr.','RB','JAX',82,41,8.7,'RB depth piece per current 53-man roster; 8.7 proj PPG (PFN consensus, not individually researched)'),
  ('Michael Wilson','WR','ARI',83,42,10.3,'WR depth piece per current 53-man roster; 10.3 proj PPG (PFN consensus, not individually researched)'),
  ('Aaron Jones Sr.','RB','MIN',84,42,8.7,'RB depth piece per current 53-man roster; 8.7 proj PPG (PFN consensus, not individually researched)'),
  ('Courtland Sutton','WR','DEN',85,43,10.2,'WR depth piece per current 53-man roster; 10.2 proj PPG (PFN consensus, not individually researched)'),
  ('Zach Charbonnet','RB','SEA',86,43,8.7,'RB depth piece per current 53-man roster; 8.7 proj PPG (PFN consensus, not individually researched)'),
  ('Chris Godwin Jr.','WR','TB',87,44,10.2,'WR depth piece per current 53-man roster; 10.2 proj PPG (PFN consensus, not individually researched)'),
  ('Woody Marks','RB','HOU',88,44,7.5,'RB depth piece per current 53-man roster; 7.5 proj PPG (PFN consensus, not individually researched)'),
  ('Khalil Shakir','WR','BUF',89,45,10.2,'WR depth piece per current 53-man roster; 10.2 proj PPG (PFN consensus, not individually researched)'),
  ('Tyler Allgeier','RB','ARI',90,45,7.5,'Cardinals depth, competing for goal-line work'),
  ('Makai Lemon','WR','PHI',91,46,10.2,'WR depth piece per current 53-man roster; 10.2 proj PPG (PFN consensus, not individually researched)'),
  ('Keaton Mitchell','RB','LAC',92,46,7.5,'RB depth piece per current 53-man roster; 7.5 proj PPG (PFN consensus, not individually researched)'),
  ('De''Zhaun Stribling','WR','SF',93,47,9.9,'WR depth piece per current 53-man roster; 9.9 proj PPG (PFN consensus, not individually researched)'),
  ('Mike Washington Jr.','RB','LV',94,47,6.8,'RB depth piece per current 53-man roster; 6.8 proj PPG (PFN consensus, not individually researched)'),
  ('Jordan Addison','WR','MIN',95,48,9.8,'WR depth piece per current 53-man roster; 9.8 proj PPG (PFN consensus, not individually researched)'),
  ('Isiah Pacheco','RB','DET',96,48,6.8,'Now with Detroit after leaving Kansas City'),
  ('Rashid Shaheed','WR','SEA',97,49,9.8,'WR depth piece per current 53-man roster; 9.8 proj PPG (PFN consensus, not individually researched)'),
  ('Tank Bigsby','RB','PHI',98,49,6.8,'RB depth piece per current 53-man roster; 6.8 proj PPG (PFN consensus, not individually researched)'),
  ('Romeo Doubs','WR','NE',99,50,9.8,'WR depth piece per current 53-man roster; 9.8 proj PPG (PFN consensus, not individually researched)'),
  ('Jonah Coleman','RB','DEN',100,50,6.8,'RB depth piece per current 53-man roster; 6.8 proj PPG (PFN consensus, not individually researched)'),
  ('Alec Pierce','WR','IND',101,51,9.8,'WR depth piece per current 53-man roster; 9.8 proj PPG (PFN consensus, not individually researched)'),
  ('Tyjae Spears','RB','TEN',102,51,6.8,'RB depth piece per current 53-man roster; 6.8 proj PPG (PFN consensus, not individually researched)'),
  ('KC Concepcion','WR','CLE',103,52,9.8,'WR depth piece per current 53-man roster; 9.8 proj PPG (PFN consensus, not individually researched)'),
  ('Dylan Sampson','RB','CLE',104,52,6.8,'RB depth piece per current 53-man roster; 6.8 proj PPG (PFN consensus, not individually researched)'),
  ('Xavier Worthy','WR','KC',105,53,9.8,'WR depth piece per current 53-man roster; 9.8 proj PPG (PFN consensus, not individually researched)'),
  ('Nick Singleton','RB','TEN',106,53,6.5,'RB depth piece per current 53-man roster; 6.5 proj PPG (PFN consensus, not individually researched)'),
  ('Jordyn Tyson','WR','NO',107,54,9.8,'WR depth piece per current 53-man roster; 9.8 proj PPG (PFN consensus, not individually researched)'),
  ('Brian Robinson Jr.','RB','ATL',108,54,6.5,'RB depth piece per current 53-man roster; 6.5 proj PPG (PFN consensus, not individually researched)'),
  ('Matthew Golden','WR','GB',109,55,8.4,'WR depth piece per current 53-man roster; 8.4 proj PPG (PFN consensus, not individually researched)'),
  ('Kimani Vidal','RB','LAC',110,55,6.5,'RB depth piece per current 53-man roster; 6.5 proj PPG (PFN consensus, not individually researched)'),
  ('Deebo Samuel Sr.','WR','SF',111,56,8.4,'WR depth piece per current 53-man roster; 8.4 proj PPG (PFN consensus, not individually researched)'),
  ('Sean Tucker','RB','TB',112,56,6.5,'RB depth piece per current 53-man roster; 6.5 proj PPG (PFN consensus, not individually researched)'),
  ('Jalen Coker','WR','CAR',113,57,8.4,'WR depth piece per current 53-man roster; 8.4 proj PPG (PFN consensus, not individually researched)'),
  ('Devin Singletary','RB','NYG',114,57,6.0,'RB depth piece per current 53-man roster; 6.0 proj PPG (PFN consensus, not individually researched)'),
  ('Tre Tucker','WR','LV',115,58,8.4,'WR depth piece per current 53-man roster; 8.4 proj PPG (PFN consensus, not individually researched)'),
  ('Ray Davis','RB','BUF',116,58,6.0,'RB depth piece per current 53-man roster; 6.0 proj PPG (PFN consensus, not individually researched)'),
  ('Travis Hunter','WR','JAX',117,59,8.4,'WR depth piece per current 53-man roster; 8.4 proj PPG (PFN consensus, not individually researched)'),
  ('Najee Harris','RB','NYG',118,59,6.0,'RB depth piece per current 53-man roster; 6.0 proj PPG (PFN consensus, not individually researched)'),
  ('Jalen McMillan','WR','TB',119,60,8.4,'WR depth piece per current 53-man roster; 8.4 proj PPG (PFN consensus, not individually researched)'),
  ('Kaytron Allen','RB','WAS',120,60,5.2,'RB depth piece per current 53-man roster; 5.2 proj PPG (PFN consensus, not individually researched)'),
  ('Jerry Jeudy','WR','CLE',121,61,8.4,'WR depth piece per current 53-man roster; 8.4 proj PPG (PFN consensus, not individually researched)'),
  ('Braelon Allen','RB','NYJ',122,61,5.2,'RB depth piece per current 53-man roster; 5.2 proj PPG (PFN consensus, not individually researched)'),
  ('Keenan Allen','WR','IND',123,62,7.9,'WR depth piece per current 53-man roster; 7.9 proj PPG (PFN consensus, not individually researched)'),
  ('Kaleb Johnson','RB','GB',124,62,5.2,'RB depth piece per current 53-man roster; 5.2 proj PPG (PFN consensus, not individually researched)'),
  ('Ryan Flournoy','WR','DAL',125,63,7.9,'WR depth piece per current 53-man roster; 7.9 proj PPG (PFN consensus, not individually researched)'),
  ('Jaylen Wright','RB','MIA',126,63,5.2,'RB depth piece per current 53-man roster; 5.2 proj PPG (PFN consensus, not individually researched)'),
  ('Jauan Jennings','WR','MIN',127,64,7.9,'WR depth piece per current 53-man roster; 7.9 proj PPG (PFN consensus, not individually researched)'),
  ('James Conner','RB','ARI',128,64,5.2,'RB depth piece per current 53-man roster; 5.2 proj PPG (PFN consensus, not individually researched)'),
  ('Jalen Nailor','WR','LV',129,65,7.8,'WR depth piece per current 53-man roster; 7.8 proj PPG (PFN consensus, not individually researched)'),
  ('Jordan James','RB','SF',130,65,5.2,'RB depth piece per current 53-man roster; 5.2 proj PPG (PFN consensus, not individually researched)'),
  ('Tre'' Harris','WR','LAC',131,66,7.8,'WR depth piece per current 53-man roster; 7.8 proj PPG (PFN consensus, not individually researched)'),
  ('Josh Jacobs','RB','GB',132,66,5.2,'Placed on the Commissioner Exempt List (Aug 30) following misdemeanor charges; timeline uncertain, court date Nov 17'),
  ('Dontayvion Wicks','WR','PHI',133,67,7.8,'WR depth piece per current 53-man roster; 7.8 proj PPG (PFN consensus, not individually researched)'),
  ('Kendre Miller','RB','NO',134,67,5.2,'RB depth piece per current 53-man roster; 5.2 proj PPG (PFN consensus, not individually researched)'),
  ('Denzel Boston','WR','CLE',135,68,7.8,'WR depth piece per current 53-man roster; 7.8 proj PPG (PFN consensus, not individually researched)'),
  ('Ollie Gordon II','RB','MIA',136,68,5.2,'RB depth piece per current 53-man roster; 5.2 proj PPG (PFN consensus, not individually researched)'),
  ('Adonai Mitchell','WR','NYJ',137,69,7.8,'WR depth piece per current 53-man roster; 7.8 proj PPG (PFN consensus, not individually researched)'),
  ('George Holani','RB','SEA',138,69,5.2,'RB depth piece per current 53-man roster; 5.2 proj PPG (PFN consensus, not individually researched)'),
  ('Omar Cooper Jr.','WR','NYJ',139,70,7.8,'WR depth piece per current 53-man roster; 7.8 proj PPG (PFN consensus, not individually researched)'),
  ('Devin Neal','RB','NO',140,70,5.2,'RB depth piece per current 53-man roster; 5.2 proj PPG (PFN consensus, not individually researched)'),
  ('Pat Bryant','WR','DEN',141,71,7.4,'WR depth piece per current 53-man roster; 7.4 proj PPG (PFN consensus, not individually researched)'),
  ('Tyrone Tracy Jr.','RB','NYG',142,71,4.7,'RB depth piece per current 53-man roster; 4.7 proj PPG (PFN consensus, not individually researched)'),
  ('Jaylin Noel','WR','HOU',143,72,7.4,'WR depth piece per current 53-man roster; 7.4 proj PPG (PFN consensus, not individually researched)'),
  ('Alvin Kamara','RB','NO',144,72,4.4,'Sprained MCL this preseason, expected out roughly a month'),
  ('Kayshon Boutte','WR','HOU',145,73,7.4,'WR depth piece per current 53-man roster; 7.4 proj PPG (PFN consensus, not individually researched)'),
  ('Isaiah Davis','RB','NYJ',146,73,4.4,'RB depth piece per current 53-man roster; 4.4 proj PPG (PFN consensus, not individually researched)'),
  ('Malachi Fields','WR','NYG',147,74,7.4,'WR depth piece per current 53-man roster; 7.4 proj PPG (PFN consensus, not individually researched)'),
  ('Emanuel Wilson','RB','SEA',148,74,4.4,'RB depth piece per current 53-man roster; 4.4 proj PPG (PFN consensus, not individually researched)'),
  ('Troy Franklin','WR','DEN',149,75,7.4,'WR depth piece per current 53-man roster; 7.4 proj PPG (PFN consensus, not individually researched)'),
  ('Emmett Johnson','RB','KC',150,75,4.4,'RB depth piece per current 53-man roster; 4.4 proj PPG (PFN consensus, not individually researched)'),
  ('Rashod Bateman','WR','BAL',151,76,7.1,'WR depth piece per current 53-man roster; 7.1 proj PPG (PFN consensus, not individually researched)'),
  ('Samaje Perine','RB','CIN',152,76,4.4,'RB depth piece per current 53-man roster; 4.4 proj PPG (PFN consensus, not individually researched)'),
  ('Tank Dell','WR','HOU',153,77,7.1,'WR depth piece per current 53-man roster; 7.1 proj PPG (PFN consensus, not individually researched)'),
  ('Malik Davis','RB','DAL',154,77,4.4,'RB depth piece per current 53-man roster; 4.4 proj PPG (PFN consensus, not individually researched)'),
  ('Christian Kirk','WR','SF',155,78,7.1,'WR depth piece per current 53-man roster; 7.1 proj PPG (PFN consensus, not individually researched)'),
  ('Seth McGowan','RB','IND',156,78,4.4,'RB depth piece per current 53-man roster; 4.4 proj PPG (PFN consensus, not individually researched)'),
  ('Isaac TeSlaa','WR','DET',157,79,7.1,'WR depth piece per current 53-man roster; 7.1 proj PPG (PFN consensus, not individually researched)'),
  ('Justice Hill','RB','BAL',158,79,4.4,'RB depth piece per current 53-man roster; 4.4 proj PPG (PFN consensus, not individually researched)'),
  ('Calvin Ridley','WR','TEN',159,80,7.1,'WR depth piece per current 53-man roster; 7.1 proj PPG (PFN consensus, not individually researched)'),
  ('Brashard Smith','RB','KC',160,80,4.4,'RB depth piece per current 53-man roster; 4.4 proj PPG (PFN consensus, not individually researched)'),
  ('Chimere Dike','WR','TEN',161,81,7.1,'WR depth piece per current 53-man roster; 7.1 proj PPG (PFN consensus, not individually researched)'),
  ('Ty Johnson','RB','BUF',162,81,4.4,'RB depth piece per current 53-man roster; 4.4 proj PPG (PFN consensus, not individually researched)'),
  ('Cooper Kupp','WR','SEA',163,82,6.6,'Rams'' complementary receiver behind Nacua; would see added volume if Nacua misses time'),
  ('Demond Claiborne','RB','MIN',164,82,4.4,'RB depth piece per current 53-man roster; 4.4 proj PPG (PFN consensus, not individually researched)'),
  ('Darnell Mooney','WR','NYG',165,83,6.6,'WR depth piece per current 53-man roster; 6.6 proj PPG (PFN consensus, not individually researched)'),
  ('Jarquez Hunter','RB','MIA',166,83,4.4,'RB depth piece per current 53-man roster; 4.4 proj PPG (PFN consensus, not individually researched)'),
  ('Elic Ayomanor','WR','TEN',167,84,6.6,'WR depth piece per current 53-man roster; 6.6 proj PPG (PFN consensus, not individually researched)'),
  ('Jaleel McLaughlin','RB','DEN',168,84,4.4,'RB depth piece per current 53-man roster; 4.4 proj PPG (PFN consensus, not individually researched)'),
  ('Tyquan Thornton','WR','KC',169,85,6.6,'WR depth piece per current 53-man roster; 6.6 proj PPG (PFN consensus, not individually researched)'),
  ('Adam Randall','RB','BAL',170,85,4.4,'RB depth piece per current 53-man roster; 4.4 proj PPG (PFN consensus, not individually researched)'),
  ('Zachariah Branch','WR','ATL',171,86,6.1,'WR depth piece per current 53-man roster; 6.1 proj PPG (PFN consensus, not individually researched)'),
  ('LeQuint Allen Jr.','RB','JAX',172,86,3.5,'RB depth piece per current 53-man roster; 3.5 proj PPG (PFN consensus, not individually researched)'),
  ('Keon Coleman','WR','BUF',173,87,6.1,'WR depth piece per current 53-man roster; 6.1 proj PPG (PFN consensus, not individually researched)'),
  ('Malik Washington','WR','MIA',174,88,6.1,'WR depth piece per current 53-man roster; 6.1 proj PPG (PFN consensus, not individually researched)'),
  ('Trevor Etienne','RB','CAR',175,88,3.5,'RB depth piece per current 53-man roster; 3.5 proj PPG (PFN consensus, not individually researched)'),
  ('Devaughn Vele','WR','NO',176,89,6.1,'WR depth piece per current 53-man roster; 6.1 proj PPG (PFN consensus, not individually researched)'),
  ('DJ Giddens','RB','IND',177,89,3.5,'RB depth piece per current 53-man roster; 3.5 proj PPG (PFN consensus, not individually researched)'),
  ('Jack Bech','WR','LV',178,90,6.1,'WR depth piece per current 53-man roster; 6.1 proj PPG (PFN consensus, not individually researched)'),
  ('Audric Estime','RB','NO',179,90,3.5,'RB depth piece per current 53-man roster; 3.5 proj PPG (PFN consensus, not individually researched)'),
  ('Kyle Williams','WR','NE',180,91,6.1,'WR depth piece per current 53-man roster; 6.1 proj PPG (PFN consensus, not individually researched)'),
  ('Chris Brooks','RB','GB',181,91,3.2,'RB depth piece per current 53-man roster; 3.2 proj PPG (PFN consensus, not individually researched)'),
  ('Darius Slayton','WR','NYG',182,92,6.1,'WR depth piece per current 53-man roster; 6.1 proj PPG (PFN consensus, not individually researched)'),
  ('Bam Knight','RB','ARI',183,92,3.2,'RB depth piece per current 53-man roster; 3.2 proj PPG (PFN consensus, not individually researched)'),
  ('Tory Horton','WR','SEA',184,93,6.1,'WR depth piece per current 53-man roster; 6.1 proj PPG (PFN consensus, not individually researched)'),
  ('Jerome Ford','RB','WAS',185,93,3.2,'RB depth piece per current 53-man roster; 3.2 proj PPG (PFN consensus, not individually researched)'),
  ('Elijah Sarratt','WR','BAL',186,94,6.1,'WR depth piece per current 53-man roster; 6.1 proj PPG (PFN consensus, not individually researched)'),
  ('Isaac Guerendo','RB','SF',187,94,3.2,'RB depth piece per current 53-man roster; 3.2 proj PPG (PFN consensus, not individually researched)'),
  ('Marvin Mims Jr.','WR','DEN',188,95,6.1,'WR depth piece per current 53-man roster; 6.1 proj PPG (PFN consensus, not individually researched)'),
  ('Dylan Laube','RB','LV',189,95,3.2,'RB depth piece per current 53-man roster; 3.2 proj PPG (PFN consensus, not individually researched)'),
  ('Mack Hollins','WR','NE',190,96,6.1,'WR depth piece per current 53-man roster; 6.1 proj PPG (PFN consensus, not individually researched)'),
  ('Kaelon Black','RB','SF',191,96,3.2,'RB depth piece per current 53-man roster; 3.2 proj PPG (PFN consensus, not individually researched)'),
  ('Treylon Burks','WR','WAS',192,97,6.1,'WR depth piece per current 53-man roster; 6.1 proj PPG (PFN consensus, not individually researched)'),
  ('Ja''Kobi Lane','WR','BAL',193,98,6.1,'WR depth piece per current 53-man roster; 6.1 proj PPG (PFN consensus, not individually researched)'),
  ('Tahj Brooks','RB','CIN',194,98,3.2,'RB depth piece per current 53-man roster; 3.2 proj PPG (PFN consensus, not individually researched)'),
  ('Xavier Legette','WR','CAR',195,100,6.1,'WR depth piece per current 53-man roster; 6.1 proj PPG (PFN consensus, not individually researched)'),
  ('Trey Benson','RB','ARI',196,100,3.2,'RB depth piece per current 53-man roster; 3.2 proj PPG (PFN consensus, not individually researched)'),
  ('Caleb Douglas','WR','MIA',197,101,6.1,'WR depth piece per current 53-man roster; 6.1 proj PPG (PFN consensus, not individually researched)'),
  ('Germie Bernard','WR','PIT',198,102,6.1,'WR depth piece per current 53-man roster; 6.1 proj PPG (PFN consensus, not individually researched)'),
  ('Eli Heidenreich','RB','PIT',199,102,3.2,'RB depth piece per current 53-man roster; 3.2 proj PPG (PFN consensus, not individually researched)'),
  ('Andrei Iosivas','WR','CIN',200,103,5.0,'WR depth piece per current 53-man roster; 5.0 proj PPG (PFN consensus, not individually researched)'),
  ('Isaiah Bond','WR','CLE',201,104,5.0,'WR depth piece per current 53-man roster; 5.0 proj PPG (PFN consensus, not individually researched)'),
  ('Chris Bell','WR','MIA',202,105,5.0,'WR depth piece per current 53-man roster; 5.0 proj PPG (PFN consensus, not individually researched)'),
  ('Hollywood Brown','WR','PHI',203,106,5.0,'WR depth piece per current 53-man roster; 5.0 proj PPG (PFN consensus, not individually researched)'),
  ('Brandon Aiyuk','WR','SF',204,107,5.0,'WR depth piece per current 53-man roster; 5.0 proj PPG (PFN consensus, not individually researched)'),
  ('Will Shipley','RB','PHI',205,107,3.0,'RB depth piece per current 53-man roster; 3.0 proj PPG (PFN consensus, not individually researched)'),
  ('Jahan Dotson','WR','ATL',206,108,5.0,'WR depth piece per current 53-man roster; 5.0 proj PPG (PFN consensus, not individually researched)'),
  ('Antonio Williams','WR','WAS',207,109,5.0,'WR depth piece per current 53-man roster; 5.0 proj PPG (PFN consensus, not individually researched)'),
  ('Xavier Hutchinson','WR','HOU',208,110,5.0,'WR depth piece per current 53-man roster; 5.0 proj PPG (PFN consensus, not individually researched)'),
  ('Calvin Austin III','WR','NYG',209,111,5.0,'WR depth piece per current 53-man roster; 5.0 proj PPG (PFN consensus, not individually researched)'),
  ('Raheim Sanders','RB','CLE',210,111,1.6,'RB depth piece per current 53-man roster; 1.6 proj PPG (PFN consensus, not individually researched)'),
  ('DeMario Douglas','WR','NE',211,112,5.0,'WR depth piece per current 53-man roster; 5.0 proj PPG (PFN consensus, not individually researched)'),
  ('Savion Williams','WR','GB',212,113,4.8,'WR depth piece per current 53-man roster; 4.8 proj PPG (PFN consensus, not individually researched)'),
  ('Tez Johnson','WR','TB',213,114,4.8,'WR depth piece per current 53-man roster; 4.8 proj PPG (PFN consensus, not individually researched)'),
  ('J''Mari Taylor','RB','JAX',214,114,1.6,'RB depth piece per current 53-man roster; 1.6 proj PPG (PFN consensus, not individually researched)'),
  ('Skyler Bell','WR','BUF',215,115,4.8,'WR depth piece per current 53-man roster; 4.8 proj PPG (PFN consensus, not individually researched)'),
  ('Roman Hemby','RB','LV',216,115,null,'RB depth piece per current 53-man roster; n/a proj PPG (PFN consensus, not individually researched)'),
  ('Malik Benson','WR','LV',217,116,4.8,'WR depth piece per current 53-man roster; 4.8 proj PPG (PFN consensus, not individually researched)'),
  ('Ted Hurst','WR','TB',218,117,4.8,'WR depth piece per current 53-man roster; 4.8 proj PPG (PFN consensus, not individually researched)'),
  ('Konata Mumpfield','WR','LAR',219,118,3.9,'WR depth piece per current 53-man roster; 3.9 proj PPG (PFN consensus, not individually researched)'),
  ('Olamide Zaccheaus','WR','ATL',220,119,3.9,'WR depth piece per current 53-man roster; 3.9 proj PPG (PFN consensus, not individually researched)'),
  ('Luke McCaffrey','WR','WAS',221,120,3.9,'WR depth piece per current 53-man roster; 3.9 proj PPG (PFN consensus, not individually researched)'),
  ('Dont''e Thornton Jr.','WR','LV',222,121,3.9,'WR depth piece per current 53-man roster; 3.9 proj PPG (PFN consensus, not individually researched)'),
  ('Demarcus Robinson','WR','SF',223,122,3.9,'WR depth piece per current 53-man roster; 3.9 proj PPG (PFN consensus, not individually researched)'),
  ('Jalen Royals','WR','KC',224,123,3.9,'WR depth piece per current 53-man roster; 3.9 proj PPG (PFN consensus, not individually researched)'),
  ('Tutu Atwell','WR','LAR',225,124,3.9,'WR depth piece per current 53-man roster; 3.9 proj PPG (PFN consensus, not individually researched)'),
  ('John Metchie III','WR','CAR',226,125,3.9,'WR depth piece per current 53-man roster; 3.9 proj PPG (PFN consensus, not individually researched)'),
  ('Joshua Palmer','WR','BUF',227,126,3.9,'WR depth piece per current 53-man roster; 3.9 proj PPG (PFN consensus, not individually researched)'),
  ('Kevin Coleman Jr.','WR','MIA',228,127,3.9,'WR depth piece per current 53-man roster; 3.9 proj PPG (PFN consensus, not individually researched)'),
  ('Jaylin Lane','WR','WAS',229,128,3.9,'WR depth piece per current 53-man roster; 3.9 proj PPG (PFN consensus, not individually researched)'),
  ('Xavier Restrepo','WR','TEN',230,129,3.9,'WR depth piece per current 53-man roster; 3.9 proj PPG (PFN consensus, not individually researched)'),
  ('Brenen Thompson','WR','LAC',231,130,3.9,'WR depth piece per current 53-man roster; 3.9 proj PPG (PFN consensus, not individually researched)'),
  ('Colbie Young','WR','CIN',232,134,3.9,'WR depth piece per current 53-man roster; 3.9 proj PPG (PFN consensus, not individually researched)'),
  ('Tai Felton','WR','MIN',233,135,3.9,'WR depth piece per current 53-man roster; 3.9 proj PPG (PFN consensus, not individually researched)'),
  ('Antwane Wells Jr.','WR','ATL',234,136,3.6,'WR depth piece per current 53-man roster; 3.6 proj PPG (PFN consensus, not individually researched)'),
  ('Chris Brazzell II','WR','CAR',235,137,3.6,'WR depth piece per current 53-man roster; 3.6 proj PPG (PFN consensus, not individually researched)'),
  ('Jalen Tolbert','WR','MIA',236,139,3.3,'WR depth piece per current 53-man roster; 3.3 proj PPG (PFN consensus, not individually researched)'),
  ('KaVontae Turpin','WR','DAL',237,141,3.3,'WR depth piece per current 53-man roster; 3.3 proj PPG (PFN consensus, not individually researched)'),
  ('Zavion Thomas','WR','CHI',238,142,3.3,'WR depth piece per current 53-man roster; 3.3 proj PPG (PFN consensus, not individually researched)'),
  ('Deion Burks','WR','IND',239,143,3.3,'WR depth piece per current 53-man roster; 3.3 proj PPG (PFN consensus, not individually researched)'),
  ('Bryce Lance','WR','NO',240,144,3.3,'WR depth piece per current 53-man roster; 3.3 proj PPG (PFN consensus, not individually researched)'),
  ('Barion Brown','WR','NO',241,145,3.3,'WR depth piece per current 53-man roster; 3.3 proj PPG (PFN consensus, not individually researched)'),
  ('Cyrus Allen','WR','KC',242,146,3.3,'WR depth piece per current 53-man roster; 3.3 proj PPG (PFN consensus, not individually researched)'),
  ('Reggie Virgil','WR','ARI',243,147,3.3,'WR depth piece per current 53-man roster; 3.3 proj PPG (PFN consensus, not individually researched)'),
  ('Brock Bowers','TE','LV',244,1,16.7,'Elite target volume at the position'),
  ('Trey McBride','TE','ARI',245,2,13.8,'Established weekly top-2 tight end'),
  ('Colston Loveland','TE','CHI',246,3,13.5,'Bears rookie with a big role already'),
  ('Tucker Kraft','TE','GB',247,4,12.8,'Was playing like a top TE before a Week 9 2025 ACL/meniscus tear; trending for Week 1'),
  ('Tyler Warren','TE','IND',248,5,11.7,'Colts rookie standout'),
  ('Sam LaPorta','TE','DET',249,6,11.3,'Fully cleared from offseason back surgery; playing for a contract extension this year'),
  ('George Kittle','TE','SF',250,7,11.3,'Established weekly starter in San Francisco'),
  ('Harold Fannin Jr.','TE','CLE',251,8,10.5,'Browns rookie carving out real target share'),
  ('Kyle Pitts Sr.','TE','ATL',252,9,10.5,'Falcons'' receiving TE option'),
  ('Dalton Kincaid','TE','BUF',253,10,10.5,'Bills'' primary receiving tight end'),
  ('Isaiah Likely','TE','NYG',254,11,10.5,'Giants tight end option'),
  ('Juwan Johnson','TE','NO',255,12,10.5,'Saints'' primary TE'),
  ('Jake Ferguson','TE','DAL',256,13,10.5,'Cowboys'' established starting TE'),
  ('Dallas Goedert','TE','PHI',257,14,9.6,'Eagles'' veteran receiving TE'),
  ('Travis Kelce','TE','KC',258,15,9.6,'Still Kansas City''s primary TE target in a changing offense'),
  ('Mark Andrews','TE','BAL',259,16,8.3,'Ravens'' veteran TE'),
  ('Chig Okonkwo','TE','WAS',260,17,8.3,'Washington''s TE option'),
  ('Hunter Henry','TE','NE',261,18,8.3,'Patriots'' veteran receiving TE'),
  ('Brenton Strange','TE','JAX',262,19,8.3,'Jaguars TE option'),
  ('Dalton Schultz','TE','HOU',263,20,8.3,'Houston''s starting TE'),
  ('AJ Barner','TE','SEA',264,21,8.0,'TE depth piece per current 53-man roster; 8.0 proj PPG (PFN consensus, not individually researched)'),
  ('Greg Dulcich','TE','MIA',265,22,8.0,'TE depth piece per current 53-man roster; 8.0 proj PPG (PFN consensus, not individually researched)'),
  ('Kenyon Sadiq','TE','NYJ',266,23,8.0,'TE depth piece per current 53-man roster; 8.0 proj PPG (PFN consensus, not individually researched)'),
  ('Terrance Ferguson','TE','LAR',267,24,8.0,'TE depth piece per current 53-man roster; 8.0 proj PPG (PFN consensus, not individually researched)'),
  ('Oronde Gadsden II','TE','LAC',268,25,7.7,'TE depth piece per current 53-man roster; 7.7 proj PPG (PFN consensus, not individually researched)'),
  ('T.J. Hockenson','TE','MIN',269,26,7.7,'TE depth piece per current 53-man roster; 7.7 proj PPG (PFN consensus, not individually researched)'),
  ('Pat Freiermuth','TE','PIT',270,27,7.7,'TE depth piece per current 53-man roster; 7.7 proj PPG (PFN consensus, not individually researched)'),
  ('Gunnar Helm','TE','TEN',271,28,7.2,'TE depth piece per current 53-man roster; 7.2 proj PPG (PFN consensus, not individually researched)'),
  ('Evan Engram','TE','DEN',272,29,7.2,'TE depth piece per current 53-man roster; 7.2 proj PPG (PFN consensus, not individually researched)'),
  ('Cade Otton','TE','TB',273,30,7.2,'TE depth piece per current 53-man roster; 7.2 proj PPG (PFN consensus, not individually researched)'),
  ('Jake Tonges','TE','SF',274,31,7.0,'TE depth piece per current 53-man roster; 7.0 proj PPG (PFN consensus, not individually researched)'),
  ('Colby Parkinson','TE','LAR',275,32,6.9,'TE depth piece per current 53-man roster; 6.9 proj PPG (PFN consensus, not individually researched)'),
  ('Theo Johnson','TE','NYG',276,33,6.9,'TE depth piece per current 53-man roster; 6.9 proj PPG (PFN consensus, not individually researched)'),
  ('Mason Taylor','TE','NYJ',277,34,6.9,'TE depth piece per current 53-man roster; 6.9 proj PPG (PFN consensus, not individually researched)'),
  ('David Njoku','TE','LAC',278,35,5.3,'TE depth piece per current 53-man roster; 5.3 proj PPG (PFN consensus, not individually researched)'),
  ('Mike Gesicki','TE','CIN',279,36,5.1,'TE depth piece per current 53-man roster; 5.1 proj PPG (PFN consensus, not individually researched)'),
  ('Michael Mayer','TE','LV',280,37,5.1,'TE depth piece per current 53-man roster; 5.1 proj PPG (PFN consensus, not individually researched)'),
  ('Eli Stowers','TE','PHI',281,38,5.1,'TE depth piece per current 53-man roster; 5.1 proj PPG (PFN consensus, not individually researched)'),
  ('Max Klare','TE','LAR',282,39,5.0,'TE depth piece per current 53-man roster; 5.0 proj PPG (PFN consensus, not individually researched)'),
  ('Darren Waller','TE','CAR',283,40,5.0,'TE depth piece per current 53-man roster; 5.0 proj PPG (PFN consensus, not individually researched)'),
  ('Darnell Washington','TE','PIT',284,42,5.0,'TE depth piece per current 53-man roster; 5.0 proj PPG (PFN consensus, not individually researched)'),
  ('Eli Raridon','TE','NE',285,43,5.0,'TE depth piece per current 53-man roster; 5.0 proj PPG (PFN consensus, not individually researched)'),
  ('John Bates','TE','WAS',286,44,5.0,'TE depth piece per current 53-man roster; 5.0 proj PPG (PFN consensus, not individually researched)'),
  ('Oscar Delp','TE','NO',287,45,4.7,'TE depth piece per current 53-man roster; 4.7 proj PPG (PFN consensus, not individually researched)'),
  ('Tyler Higbee','TE','LAR',288,47,4.0,'TE depth piece per current 53-man roster; 4.0 proj PPG (PFN consensus, not individually researched)'),
  ('Sam Roush','TE','CHI',289,48,4.0,'TE depth piece per current 53-man roster; 4.0 proj PPG (PFN consensus, not individually researched)'),
  ('Michael Trigg','TE','DAL',290,49,4.0,'TE depth piece per current 53-man roster; 4.0 proj PPG (PFN consensus, not individually researched)'),
  ('Tanner Koziol','TE','JAX',291,50,4.0,'TE depth piece per current 53-man roster; 4.0 proj PPG (PFN consensus, not individually researched)'),
  ('Elijah Arroyo','TE','SEA',292,51,4.0,'TE depth piece per current 53-man roster; 4.0 proj PPG (PFN consensus, not individually researched)'),
  ('Jack Endries','TE','CIN',293,52,4.0,'TE depth piece per current 53-man roster; 4.0 proj PPG (PFN consensus, not individually researched)'),
  ('Noah Gray','TE','KC',294,53,3.8,'TE depth piece per current 53-man roster; 3.8 proj PPG (PFN consensus, not individually researched)'),
  ('Ja''Tavion Sanders','TE','CAR',295,54,3.8,'TE depth piece per current 53-man roster; 3.8 proj PPG (PFN consensus, not individually researched)'),
  ('Joe Royer','TE','CLE',296,55,3.8,'TE depth piece per current 53-man roster; 3.8 proj PPG (PFN consensus, not individually researched)'),
  ('Noah Fant','TE','NO',297,57,3.8,'TE depth piece per current 53-man roster; 3.8 proj PPG (PFN consensus, not individually researched)'),
  ('Dallen Bentley','TE','DEN',298,58,3.2,'TE depth piece per current 53-man roster; 3.2 proj PPG (PFN consensus, not individually researched)'),
  ('Dawson Knox','TE','BUF',299,59,3.2,'TE depth piece per current 53-man roster; 3.2 proj PPG (PFN consensus, not individually researched)'),
  ('Cole Kmet','TE','CHI',300,60,3.2,'TE depth piece per current 53-man roster; 3.2 proj PPG (PFN consensus, not individually researched)'),
  ('RJ Maryland','TE','GB',301,61,3.2,'TE depth piece per current 53-man roster; 3.2 proj PPG (PFN consensus, not individually researched)'),
  ('Josh Allen','QB','BUF',302,1,23.6,'Reigning fantasy QB1 producer; rushing floor plus elite arm talent'),
  ('Drake Maye','QB','NE',303,2,22.1,'Added A.J. Brown and Romeo Doubs this offseason; year-2 breakout profile'),
  ('Lamar Jackson','QB','BAL',304,3,21.5,'Elite rushing floor at the position, weekly top-5 upside'),
  ('Jayden Daniels','QB','WAS',305,4,20.7,'Dual-threat, now throwing to Stefon Diggs after Aug signing'),
  ('Joe Burrow','QB','CIN',306,5,19.2,'Elite volume passer when healthy; injury history worth monitoring'),
  ('Jalen Hurts','QB','PHI',307,6,18.7,'Goal-line rushing role keeps weekly floor high even in down passing weeks'),
  ('Caleb Williams','QB','CHI',308,7,18.3,'Retained DJ Moore, better protection; year-2 leap candidate'),
  ('Justin Herbert','QB','LAC',309,8,18.3,'Strong arm on a thin weapons crop; high pass-volume offense'),
  ('Jaxson Dart','QB','NYG',310,9,18.1,'Big jump in year-2 analyst rankings after rookie flashes'),
  ('Trevor Lawrence','QB','JAX',311,10,17.7,'Led Jacksonville to the AFC South last year; established weekly starter'),
  ('Dak Prescott','QB','DAL',312,11,17.7,'Now has George Pickens as a true co-WR1 next to CeeDee Lamb'),
  ('Bo Nix','QB','DEN',313,12,16.1,'Gets a boost from the Jaylen Waddle trade addition'),
  ('Patrick Mahomes II','QB','KC',314,13,16.1,'Recovering from torn ACL/LCL; Week 1 workload uncertain'),
  ('Brock Purdy','QB','SF',315,14,15.8,'Loaded WR room after the Mike Evans trade addition'),
  ('Jordan Love','QB','GB',316,15,15.8,'Tucker Kraft (healthy) plus a deep WR corps to throw to'),
  ('Matthew Stafford','QB','LAR',317,16,15.5,'Veteran, Davante Adams and Puka Nacua both in the mix'),
  ('Kyler Murray','QB','MIN',318,17,15.5,'Fresh start in Minnesota after Arizona released him'),
  ('Jared Goff','QB','DET',319,18,15.5,'Efficient offense, Gibbs and St. Brown as top weapons'),
  ('Tyler Shough','QB','NO',320,19,14.6,'Inherited the Saints'' starting job'),
  ('Malik Willis','QB','MIA',321,20,14.6,'New Dolphins starter after Tua''s release; run-first scheme being built around him'),
  ('Baker Mayfield','QB','TB',322,21,14.0,'Emeka Egbuka emerging as a real second option'),
  ('Daniel Jones','QB','IND',323,22,13.8,'Colts kept Anthony Richardson as the backup plan behind him'),
  ('C.J. Stroud','QB','HOU',324,23,13.8,'Nico Collins plus new addition David Montgomery in the backfield'),
  ('Sam Darnold','QB','SEA',325,24,13.8,'Continues as Seattle''s starter'),
  ('Cam Ward','QB','TEN',326,25,13.8,'Titans'' starter, throwing to rookie Carnell Tate and Calvin Ridley'),
  ('Bryce Young','QB','CAR',327,26,13.8,'Third year as Panthers starter'),
  ('Jacoby Brissett','QB','ARI',328,27,13.5,'Cardinals'' presumptive starter'),
  ('Aaron Rodgers','QB','PIT',329,28,13.5,'Veteran addition in Pittsburgh'),
  ('Geno Smith','QB','NYJ',330,29,12.4,'QB depth piece per current 53-man roster; 12.4 proj PPG (PFN consensus, not individually researched)'),
  ('Tua Tagovailoa','QB','ATL',331,30,12.4,'QB depth piece per current 53-man roster; 12.4 proj PPG (PFN consensus, not individually researched)'),
  ('Kirk Cousins','QB','LV',332,31,12.4,'QB depth piece per current 53-man roster; 12.4 proj PPG (PFN consensus, not individually researched)'),
  ('Fernando Mendoza','QB','LV',333,32,12.4,'QB depth piece per current 53-man roster; 12.4 proj PPG (PFN consensus, not individually researched)'),
  ('Michael Penix Jr.','QB','ATL',334,33,12.4,'QB depth piece per current 53-man roster; 12.4 proj PPG (PFN consensus, not individually researched)'),
  ('Deshaun Watson','QB','CLE',335,34,12.4,'QB depth piece per current 53-man roster; 12.4 proj PPG (PFN consensus, not individually researched)'),
  ('Shedeur Sanders','QB','CLE',336,35,11.2,'QB depth piece per current 53-man roster; 11.2 proj PPG (PFN consensus, not individually researched)'),
  ('Justin Fields','QB','KC',337,36,11.2,'QB depth piece per current 53-man roster; 11.2 proj PPG (PFN consensus, not individually researched)'),
  ('J.J. McCarthy','QB','MIN',338,37,11.2,'QB depth piece per current 53-man roster; 11.2 proj PPG (PFN consensus, not individually researched)'),
  ('Mac Jones','QB','SF',339,38,11.2,'QB depth piece per current 53-man roster; 11.2 proj PPG (PFN consensus, not individually researched)'),
  ('Ty Simpson','QB','LAR',340,39,11.2,'QB depth piece per current 53-man roster; 11.2 proj PPG (PFN consensus, not individually researched)'),
  ('Jameis Winston','QB','NYG',341,40,11.2,'QB depth piece per current 53-man roster; 11.2 proj PPG (PFN consensus, not individually researched)'),
  ('Carson Beck','QB','ARI',342,41,11.2,'QB depth piece per current 53-man roster; 11.2 proj PPG (PFN consensus, not individually researched)'),
  ('Dillon Gabriel','QB','CLE',343,42,11.2,'QB depth piece per current 53-man roster; 11.2 proj PPG (PFN consensus, not individually researched)'),
  ('Jack Strand','QB','ATL',344,43,11.2,'QB depth piece per current 53-man roster; 11.2 proj PPG (PFN consensus, not individually researched)'),
  ('Marcus Mariota','QB','WAS',345,44,10.0,'QB depth piece per current 53-man roster; 10.0 proj PPG (PFN consensus, not individually researched)'),
  ('Anthony Richardson Sr.','QB','IND',346,45,10.0,'QB depth piece per current 53-man roster; 10.0 proj PPG (PFN consensus, not individually researched)'),
  ('Drew Allar','QB','PIT',347,46,10.0,'QB depth piece per current 53-man roster; 10.0 proj PPG (PFN consensus, not individually researched)'),
  ('Joe Milton III','QB','DAL',348,47,8.6,'QB depth piece per current 53-man roster; 8.6 proj PPG (PFN consensus, not individually researched)'),
  ('Taylen Green','QB','CLE',349,48,8.6,'QB depth piece per current 53-man roster; 8.6 proj PPG (PFN consensus, not individually researched)'),
  ('Cole Payton','QB','PHI',350,49,null,'QB depth piece per current 53-man roster; n/a proj PPG (PFN consensus, not individually researched)'),
  ('Cade Klubnik','QB','NYJ',351,50,null,'QB depth piece per current 53-man roster; n/a proj PPG (PFN consensus, not individually researched)'),
  ('Garrett Nussmeier','QB','KC',352,51,null,'QB depth piece per current 53-man roster; n/a proj PPG (PFN consensus, not individually researched)'),
  ('Miller Moss','QB','CHI',353,52,null,'QB depth piece per current 53-man roster; n/a proj PPG (PFN consensus, not individually researched)'),
  ('Denver Broncos','DEF','DEN',354,1,9.9,'Top-ranked fantasy defense entering the season'),
  ('Houston Texans','DEF','HOU',355,2,9.2,'Strong pass rush, favorable defensive scheme'),
  ('Los Angeles Rams','DEF','LAR',356,3,8.3,'Elite defensive roster talent'),
  ('Seattle Seahawks','DEF','SEA',357,4,8.2,'Aggressive, turnover-generating unit'),
  ('Philadelphia Eagles','DEF','PHI',358,5,8.0,'Deep, talented defensive front'),
  ('New England Patriots','DEF','NE',359,6,7.6,'DST6 per current PFN consensus; 7.6 proj PPG'),
  ('Minnesota Vikings','DEF','MIN',360,7,7.5,'DST7 per current PFN consensus; 7.5 proj PPG'),
  ('Pittsburgh Steelers','DEF','PIT',361,8,7.3,'DST8 per current PFN consensus; 7.3 proj PPG'),
  ('Baltimore Ravens','DEF','BAL',362,9,7.2,'DST9 per current PFN consensus; 7.2 proj PPG'),
  ('Jacksonville Jaguars','DEF','JAX',363,10,7.1,'DST10 per current PFN consensus; 7.1 proj PPG'),
  ('Los Angeles Chargers','DEF','LAC',364,11,6.9,'DST11 per current PFN consensus; 6.9 proj PPG'),
  ('Green Bay Packers','DEF','GB',365,12,6.8,'DST12 per current PFN consensus; 6.8 proj PPG'),
  ('Kansas City Chiefs','DEF','KC',366,13,6.7,'DST13 per current PFN consensus; 6.7 proj PPG'),
  ('Detroit Lions','DEF','DET',367,14,6.6,'DST14 per current PFN consensus; 6.6 proj PPG'),
  ('Buffalo Bills','DEF','BUF',368,15,6.4,'DST15 per current PFN consensus; 6.4 proj PPG'),
  ('Dallas Cowboys','DEF','DAL',369,16,6.1,'DST16 per current PFN consensus; 6.1 proj PPG'),
  ('Cleveland Browns','DEF','CLE',370,17,6.1,'DST17 per current PFN consensus; 6.1 proj PPG'),
  ('Atlanta Falcons','DEF','ATL',371,18,6.0,'DST18 per current PFN consensus; 6.0 proj PPG'),
  ('New Orleans Saints','DEF','NO',372,19,5.9,'DST19 per current PFN consensus; 5.9 proj PPG'),
  ('Indianapolis Colts','DEF','IND',373,20,5.8,'DST20 per current PFN consensus; 5.8 proj PPG'),
  ('Chicago Bears','DEF','CHI',374,21,5.6,'DST21 per current PFN consensus; 5.6 proj PPG'),
  ('Washington Commanders','DEF','WAS',375,22,5.6,'DST22 per current PFN consensus; 5.6 proj PPG'),
  ('San Francisco 49ers','DEF','SF',376,23,5.4,'DST23 per current PFN consensus; 5.4 proj PPG'),
  ('Cincinnati Bengals','DEF','CIN',377,24,5.2,'DST24 per current PFN consensus; 5.2 proj PPG'),
  ('New York Giants','DEF','NYG',378,25,5.0,'DST25 per current PFN consensus; 5.0 proj PPG'),
  ('Tampa Bay Buccaneers','DEF','TB',379,26,5.0,'DST26 per current PFN consensus; 5.0 proj PPG'),
  ('Miami Dolphins','DEF','MIA',380,27,4.9,'DST27 per current PFN consensus; 4.9 proj PPG'),
  ('Tennessee Titans','DEF','TEN',381,28,4.6,'DST28 per current PFN consensus; 4.6 proj PPG'),
  ('Carolina Panthers','DEF','CAR',382,29,4.4,'DST29 per current PFN consensus; 4.4 proj PPG'),
  ('New York Jets','DEF','NYJ',383,30,4.2,'DST30 per current PFN consensus; 4.2 proj PPG'),
  ('Arizona Cardinals','DEF','ARI',384,31,3.8,'DST31 per current PFN consensus; 3.8 proj PPG'),
  ('Las Vegas Raiders','DEF','LV',385,32,3.1,'DST32 per current PFN consensus; 3.1 proj PPG'),
  ('Brandon Aubrey','K','DAL',386,1,11.2,'Elite accuracy, high-scoring Dallas offense'),
  ('Cam Little','K','JAX',387,2,10.6,'Strong leg, Jacksonville''s improving offense'),
  ('Cameron Dicker','K','LAC',388,3,10.1,'Reliable veteran leg in a pass-heavy Chargers offense'),
  ('Ka''imi Fairbairn','K','HOU',389,4,9.6,'K4 per current depth chart; 9.6 proj PPG (PFN consensus)'),
  ('Evan McPherson','K','CIN',390,5,9.4,'K5 per current depth chart; 9.4 proj PPG (PFN consensus)'),
  ('Jason Myers','K','SEA',391,6,9.3,'K6 per current depth chart; 9.3 proj PPG (PFN consensus)'),
  ('Harrison Mevis','K','LAR',392,7,9.2,'K7 per current depth chart; 9.2 proj PPG (PFN consensus)'),
  ('Andy Borregales','K','NE',393,8,9.0,'K8 per current depth chart; 9.0 proj PPG (PFN consensus)'),
  ('Tyler Loop','K','BAL',394,9,8.8,'K9 per current depth chart; 8.8 proj PPG (PFN consensus)'),
  ('Jake Bates','K','DET',395,10,8.8,'K10 per current depth chart; 8.8 proj PPG (PFN consensus)'),
  ('Cairo Santos','K','CHI',396,11,8.6,'K11 per current depth chart; 8.6 proj PPG (PFN consensus)'),
  ('Eddy Pineiro','K','SF',397,12,8.4,'K12 per current depth chart; 8.4 proj PPG (PFN consensus)'),
  ('Chase McLaughlin','K','TB',398,13,8.4,'K13 per current depth chart; 8.4 proj PPG (PFN consensus)'),
  ('Wil Lutz','K','DEN',399,14,8.2,'K14 per current depth chart; 8.2 proj PPG (PFN consensus)'),
  ('Harrison Butker','K','KC',400,15,8.0,'K15 per current depth chart; 8.0 proj PPG (PFN consensus)'),
  ('Charlie Smyth','K','NO',401,16,8.0,'K16 per current depth chart; 8.0 proj PPG (PFN consensus)'),
  ('Chris Boswell','K','PIT',402,17,7.8,'K17 per current depth chart; 7.8 proj PPG (PFN consensus)'),
  ('Blake Grupe','K','NYJ',403,18,7.8,'K18 per current depth chart; 7.8 proj PPG (PFN consensus)'),
  ('Tyler Bass','K','BUF',404,19,7.7,'K19 per current depth chart; 7.7 proj PPG (PFN consensus)'),
  ('Joey Slye','K','TEN',405,20,7.6,'K20 per current depth chart; 7.6 proj PPG (PFN consensus)'),
  ('Chad Ryland','K','ARI',406,21,7.6,'K21 per current depth chart; 7.6 proj PPG (PFN consensus)'),
  ('Jake Elliott','K','PHI',407,22,7.4,'K22 per current depth chart; 7.4 proj PPG (PFN consensus)'),
  ('Trey Smack','K','GB',408,23,7.3,'K23 per current depth chart; 7.3 proj PPG (PFN consensus)'),
  ('Will Reichard','K','MIN',409,24,7.1,'K24 per current depth chart; 7.1 proj PPG (PFN consensus)'),
  ('Ryan Fitzgerald','K','CAR',410,25,6.9,'K25 per current depth chart; 6.9 proj PPG (PFN consensus)'),
  ('Daniel Carlson','K','NO',411,26,6.7,'K26 per current depth chart; 6.7 proj PPG (PFN consensus)'),
  ('Nick Folk','K','ATL',412,27,6.4,'K27 per current depth chart; 6.4 proj PPG (PFN consensus)'),
  ('Ben Sauls','K','NYG',413,28,6.1,'K28 per current depth chart; 6.1 proj PPG (PFN consensus)'),
  ('Jake Moody','K','BAL',414,29,5.5,'K29 per current depth chart; 5.5 proj PPG (PFN consensus)'),
  ('Andre Szmyt','K','CLE',415,30,4.9,'K30 per current depth chart; 4.9 proj PPG (PFN consensus)'),
  ('Jason Sanders','K','NYJ',416,31,4.7,'K31 per current depth chart; 4.7 proj PPG (PFN consensus)'),
  ('Spencer Shrader','K','IND',417,33,4.4,'K33 per current depth chart; 4.4 proj PPG (PFN consensus)'),
  ('Matt Gay','K','LV',418,34,4.2,'K34 per current depth chart; 4.2 proj PPG (PFN consensus)'),
  ('Riley Patterson','K','MIA',419,36,3.9,'K36 per current depth chart; 3.9 proj PPG (PFN consensus)')
),
inserted_players as (
  insert into players (full_name, position, team_id)
  select full_name, position, team_id from source_data
  returning player_id, full_name, position
),
inserted_rankings as (
  insert into player_rankings (player_id, season_year, scoring_format, overall_rank, position_rank, proj_ppg, source)
  select ip.player_id, 2026, 'half_ppr', sd.overall_rank, sd.position_rank, sd.proj_ppg,
         'PFN consensus, cross-checked ESPN/Yahoo'
  from inserted_players ip
  join source_data sd on ip.full_name = sd.full_name and ip.position = sd.position
  returning player_id
)
insert into player_updates (player_id, note_type, note_text, source)
select ip.player_id, 'context', sd.note_text, 'Claude research compilation, Sept 2026'
from inserted_players ip
join source_data sd on ip.full_name = sd.full_name and ip.position = sd.position;
